version: "0.2"
words:
  - 2bndy5
  - bndy
  - clippy
  - Despawn
  - Doherty
  - fract
  - hexdigit
  - nextest
  - rngs
  - Tetris
  - thiserror
  - timeit
ignorePaths:
  - .gitignore
  - .gitattributes
  - .vscode/**
