[package]
name = "sudoku-gen"
description = "A tool to generate/import, solve, and validate Sudoku puzzles."
version = "0.1.0"
repository.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sudoku-gen"
path = "src/main.rs"
required-features = ["bin"]

[[bench]]
name = "completed"
harness = false

[dependencies]
anyhow = { version = "1.0.103", optional = true }
clap = { version = "4.6.1", features = ["derive"], optional = true }
rand = { version = "0.10.2", features = ["alloc"] }
thiserror = "2.0.18"

[features]
clap = ["dep:clap"]
anyhow = ["dep:anyhow"]
bin = ["clap", "anyhow"]

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
