# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    rust: latest
  jobs:
    build:
      html:
        - cargo doc
    post_build:
      - mkdir -p ${READTHEDOCS_OUTPUT}/html/
      - mv target/doc/** ${READTHEDOCS_OUTPUT}/html
